# Generated by Django 3.0 on 2020-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxiuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='taxiuser',
            name='telephone',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
