# Generated by Django 3.0.2 on 2020-01-23 14:08

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 14, 8, 38, 323349, tzinfo=utc)),
        ),
    ]
