# Generated by Django 3.0.2 on 2020-01-24 02:44

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0002_employe_date_embauche'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='jour_depart',
            field=models.CharField(
                choices=[('0', 'Lundi'), ('1', 'Mardi'), ('2', 'Mercredi'), ('3', 'Jeudi'), ('4', 'Vendredi'),
                         ('5', 'Samedi'), ('6', 'Dimance')], default=4, max_length=64),
        ),
        migrations.AddField(
            model_name='voiture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 2, 44, 18, 788327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programme',
            name='heure_depart',
            field=models.CharField(choices=[('6', '6h'), ('10', '10h'), ('14', '14h'), ('19', '19h'), ('22', '22h')],
                                   max_length=64),
        ),
    ]
