# Generated by Django 3.0 on 2020-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0002_reservation_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('EN COUR', 'Encour'), ('TERMINER', 'Terminer')],
                                   default='ATTENTE', max_length=10),
        ),
    ]
