# Generated by Django 3.0.2 on 2020-01-24 03:51

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0003_auto_20200124_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guichetier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='taxi.Employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 3, 51, 5, 879935, tzinfo=utc)),
        ),
    ]
