# Generated by Django 3.0.2 on 2020-01-24 04:18

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0004_auto_20200124_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_depart',
            field=models.DateField(default=datetime.date(2020, 1, 24), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 4, 18, 38, 949487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 4, 18, 38, 951783, tzinfo=utc),
                                       verbose_name='Created at'),
        ),
    ]
