# Generated by Django 3.0.2 on 2020-01-24 05:19

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('taxi', '0005_auto_20200124_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 5, 19, 29, 44826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programme',
            name='heure_depart',
            field=models.TimeField(choices=[('6', '6h'), ('10', '10h'), ('14', '14h'), ('19', '19h'), ('22', '22h')],
                                   default=datetime.time(15, 0), max_length=64),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 5, 19, 29, 49075, tzinfo=utc),
                                       verbose_name='Created at'),
        ),
    ]
