# Generated by Django 3.0.2 on 2020-01-24 14:10

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20200124_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('REFUSER', 'Refuser'), ('ACCEPER', 'Accepter'), ('EN COUR', 'Encour'), ('TERMINER', 'Terminer')], default='ATTENTE', max_length=64),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 14, 10, 28, 972425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 14, 10, 28, 974768, tzinfo=utc), verbose_name='Created at'),
        ),
    ]
